%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Parse EyeTracker Processed Output Data file 
%
%
% Program name: parse_eyetracker_outdata.m
%
% This program gives an example of how to scan the output files generated by
% program "eyetrack_process.m". Add your own data processing code
% afterwards.
%
% Entry Requirements:
%    Run "eyetrack_process.m" on desired data file first and generate output
%    files with _scanInfo_ strings. Then run this program after specifying
%     name of the file in string "fileStr0".
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all;
filePathStr='dat/'; %this works for both unix and windows

%%%%%%%%%%%%%%%%%%%%%%%%User inputs here %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fileStr0=strcat(filePathStr,'cg_eyetrack_data_021810'); %eyetracker data file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


disp('Scanning from File. This will take a few minutes');


inFileStr0=strcat(fileStr0,'_scanInfo_');
inFileStr=strcat(inFileStr0, 'numscans', '.txt');
inFile=fopen(inFileStr, 'r');
numScans=fscanf(inFile, '%d', 1);    
fclose(inFile);


for scanNum=1:numScans,
    scanNumStr=sprintf('%d',scanNum);
    inFileStr=strcat(inFileStr0, scanNumStr, '.txt');
    inFile=fopen(inFileStr, 'r');
    
    fgets(inFile); %Scan text line
    
    numData(scanNum)=fscanf(inFile, '%d', 1);
    fclose(inFile);
end

timeIndex=zeros(numScans,max(numData));
meanX=zeros(numScans,max(numData));
meanY=zeros(numScans,max(numData));
stdX=zeros(numScans,max(numData));
stdY=zeros(numScans,max(numData));
fracPtsOutsideWindow=zeros(numScans,max(numData));

for scanNum=1:numScans, %For each scan

    scanNumStr=sprintf('%d',scanNum);
    inFileStr=strcat(inFileStr0, scanNumStr, '.txt');
    inFile=fopen(inFileStr, 'r');
    
    fgets(inFile); %Scan text line
    
    numData(scanNum)=fscanf(inFile, '%d', 1); %Number of data points in each scan
    meanX(scanNum)=fscanf(inFile, '%f', 1); % Mean of X data
    meanY(scanNum)=fscanf(inFile, '%f', 1); % Mean of Y data
    stdX(scanNum)=fscanf(inFile, '%f', 1);  % Standard deviation of X data
    stdY(scanNum)=fscanf(inFile, '%f', 1);  % Standard deviation of Y data
    fracPtsOutsideWindow(scanNum)=fscanf(inFile, '%f', 1); % Percentage of points outside fixation window

    fgets(inFile); %Scan blank line
    fgets(inFile); %Scan text line
        
    for count=1:numData(scanNum),
        timeIndex(scanNum,count)=fscanf(inFile, '%f', 1); %Time information
        xData(scanNum,count)=fscanf(inFile, '%f', 1); %X data
        yData(scanNum,count)=fscanf(inFile, '%f', 1); % Y data

        blinkInfo(scanNum,count)=fscanf(inFile, '%d', 1); % 1= Blink; 0= no blink
        saccadeInfo(scanNum,count)=fscanf(inFile, '%d', 1);% 1= Saccade; 0= no saccade
        outsideFixWindowInfo(scanNum,count)=fscanf(inFile, '%d', 1); 
               %1= outside fixation window ; 0= inside window
        
     end %end count
    
    
    fclose(inFile);
    scanNum
    
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
%%%%%%%%%%%%%%%%%%%%%%%Process data here   %%%%%%%%%%%%%%%%%%
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end %end scanNum

